const Intake2020Data = [
  {
    id: 0,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747723143/Avatar_avs1qx.avif",
    name: "Mr. Nandan Kumar",
    branch: "",
    hall: "",
    mail: "",
    linkedIn: "",
  },
  {
    id: 1,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1748290427/Nandan_Kumar_Singh_bgfigs_ga45au.avif",
    name: "Mr. Nandan Singh",
    branch: "CH",
    hall: "",
    mail: "nandankumarsingh@kgpian.iitkgp.ac.in",
    linkedIn: "",
  },
  {
    id: 2,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1748290428/Neeraj_Gartia_cbr3l1_xvgk8b.avif",
    name: "Mr. Neeraj Gartia",
    branch: "MA",
    hall: "",
    mail: "neerajgartia211002@kgpian.iitkgp.ac.in",
    linkedIn: "",
  },
  {
    id: 3,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1748290429/Pratik_Choudhury_njqkep.avif",
    name: "Mr. Pratik Choudhury",
    branch: "CH",
    hall: "",
    mail: "pratik.choudhury@kgpian.iitkgp.ac.in",
    linkedIn: "",
  },
  {
    id: 4,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747723143/Avatar_avs1qx.avif",
    name: "Mr. Priyanshu Kumar",
    branch: "",
    hall: "",
    mail: "",
    linkedIn: "",
  },
  {
    id: 5,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747723143/Avatar_avs1qx.avif",
    name: "Mr. Shubham Kumar",
    branch: "",
    hall: "",
    mail: "",
    linkedIn: "",
  },
  {
    id: 6,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747723143/Avatar_avs1qx.avif",
    name: "Mr. Soumya Ranjan",
    branch: "",
    hall: "",
    mail: "",
    linkedIn: "",
  },
  {
    id: 7,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747723143/Avatar_avs1qx.avif",
    name: "Mr. Sumit Patel",
    branch: "MA",
    hall: "",
    mail: "patelsumit.1652002@kgpian.iitkgp.ac.in",
    linkedIn: "",
  },
  {
    id: 8,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747723143/Avatar_avs1qx.avif",
    name: "Ms. Sweta Kumari",
    branch: "CH",
    hall: "",
    mail: "swetakumari@kgpian.iitkgp.ac.in",
    linkedIn: "",
  },
];

export default Intake2020Data;
