const Intake2021Data = [
  {
    id: 0,
    name: "Mr. Abhinaw Anand",
    branch: "MA",
    mail: "abhinaw12anand@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747723143/Avatar_avs1qx.avif",
    linkedIn: "",
    hall: "Nehru",
    graduated:false,
  },
  {
    id: 1,
    name: "Mr. Ajay Kr. Dhakar",
    branch: "CS",
    mail: "ajaydhaker2002@gmail.com",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747723143/Avatar_avs1qx.avif",
    linkedIn: "",
    hall: "Patel",
    graduated:false,
  },
  {
    id: 2,
    name: "Mr. Akshay Sawai",
    branch: "MI",
    mail: "akshaysawai252@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747723143/Avatar_avs1qx.avif",
    linkedIn: "",
    hall: "",
    graduated:true,
  },
  {
    id: 3,
    name: "Mr. Ashutosh",
    branch: "MA",
    mail: "ashutosh.daan@gmail.com",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1748012053/Ashutosh_wvgdts.avif",
    linkedIn: "",
    hall: "RK",
    graduated:false,
  },
  {
    id: 4,
    name: "Mr. Chhotoo Solanki",
    branch: "ME",
    mail: "chhotoosolanki11@gmail.com",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747723143/Avatar_avs1qx.avif",
    linkedIn: "",
    hall: "LBS",
    graduated:false,
  },
  {
    id: 5,
    name: "Ms. Himanshi Gupta",
    branch: "IE",
    mail: "himanshigupta@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747723143/Avatar_avs1qx.avif",
    linkedIn: "",
    hall: "",
    graduated:true,
  },
  {
    id: 6,
    name: "Ms. Mahale Harshada Nitin",
    branch: "EC",
    mail: "harshadamahale2002@gmail.com",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747723143/Avatar_avs1qx.avif",
    linkedIn: "",
    hall: "MT",
    graduated:false,
  },
  {
    id: 7,
    name: "Mr. Mingma Rinzing Lepcha",
    branch: "EC",
    mail: "mingmarlepcha2000@gmail.com",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747723143/Avatar_avs1qx.avif",
    linkedIn: "",
    hall: "MMM",
    graduated:false,
  },
  {
    id: 8,
    name: "Mr. Maheraman Indrasinh Rameshbhai",
    branch: "MA",
    mail: "indrasinhmahera1110@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747723143/Avatar_avs1qx.avif",
    linkedIn: "",
    hall: "",
    graduated:true,
  },
  {
    id: 9,
    name: "Mr. Neeraj Kumar",
    branch: "MA",
    mail: "meenaneerajkumar148@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747723143/Avatar_avs1qx.avif",
    linkedIn: "",
    hall: "",
    graduated:true,
  },
  {
    id: 10,
    name: "Mr. Nitin Rajvanshi",
    branch: "MA",
    mail: "nkraj7266@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1748290244/Nitin_Rajvanshi_mbleyw.avif",
    linkedIn: "https://www.linkedin.com/in/nitinrajvanshi/",
    hall: "Patel",
    graduated:true,
  },
  {
    id: 11,
    name: "Mr. Prajwal Kadbe",
    branch: "MI",
    mail: "kprajwal358@gmail.com",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747723143/Avatar_avs1qx.avif",
    linkedIn: "",
    hall: "RP",
    graduated:false,
  },
  {
    id: 12,
    name: "Mr. Saurabh Kumar",
    branch: "MI",
    mail: "sraj31962@gmail.com",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1748290245/Saurabh_tez2ke.avif",
    linkedIn: "https://www.linkedin.com/in/saurabh-kumar-7692b1223?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    hall: "MMM",
    graduated:false,
  },
  {
    id: 13,
    name: "Mr. Sewan Panchare",
    branch: "MA",
    mail: "sevanpanchare@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747723143/Avatar_avs1qx.avif",
    linkedIn: "",
    hall: "",
    graduated:true,
  },
  {
    id: 14,
    name: "Mr. Soumyadeep Pradhan",
    branch: "ME",
    mail: "soumyadeep265@gmail.com",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1748290245/Soumyadeep_Pradhan_txhhqi.avif",
    linkedIn: "https://in.linkedin.com/in/soumyadeep-pradhan-ab4412229",
    hall: "",
    graduated:true,
  },
  {
    id: 15,
    name: "Mr. Suman Anand",
    branch: "MA",
    mail: "ksumananand614@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747723143/Avatar_avs1qx.avif",
    linkedIn: "",
    hall: "",
    graduated:true,
  },
  {
    id: 16,
    name: "Mr. Suraj Kumar",
    branch: "CH",
    mail: "surajkumarasdf18@gmail.com",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747723143/Avatar_avs1qx.avif",
    linkedIn: "",
    hall: "LBS",
    graduated:false,
  },
];

export default Intake2021Data;
