const Intake2025Data = [
  {
    id: 0,
    name: "Mr. Anguluri Rajesh",
    branch: "MT",
    img: "https://res.cloudinary.com/dubu8yxkm/image/upload/v1754513795/Anguluri_Rajesh_qodvur.avif",
    coe: "Dakshana Valley",
    hall: "LBS",
    contacts: {
      mail: "rajeshanguluri965@gmail.com",
      linkedIn:
        "https://www.linkedin.com/in/%CA%80%E1%B4%80%E1%B4%8A%E1%B4%87%EA%9C%B1%CA%9C-rajesh-a5b518378",
      phone: "9392152216",
    },
    involvements: {
      soc: [],
      hall: [],
      council: [],
      iit: [],
      extra: "",
    },
  },
  {
    id: 1,
    name: "Mr. Aniket Biswas",
    branch: "BT",
    img: "https://res.cloudinary.com/dubu8yxkm/image/upload/v1754513795/Aniket_Biswas_xtvakl.avif",
    coe: "Dakshana Valley",
    hall: "LBS",
    contacts: {
      mail: "aniketrhythm2424@gmail.com",
      linkedIn: "https://www.linkedin.com/in/aniket-biswas-47a5a2377",
      phone: "8388801783",
    },
    involvements: {
      soc: [],
      hall: [],
      council: [],
      iit: [],
      extra: "",
    },
  },
  {
    id: 2,
    name: "Mr. Aniket Herole",
    branch: "MT",
    img: "https://res.cloudinary.com/dubu8yxkm/image/upload/v1754513796/Aniket_Herole_xmyhra.avif",
    coe: "Dakshana Valley",
    hall: "LBS",
    contacts: {
      mail: "aniketherole9@gmail.com",
      linkedIn: "https://www.linkedin.com/in/aniket-herole-4785b7377",
      phone: "9764492077",
    },
    involvements: {
      soc: ["NSSC"],
      hall: [],
      council: [],
      iit: [],
      extra: "",
    },
  },
  {
    id: 3,
    name: "Mr. Ankit Raj",
    branch: "CS",
    img: "https://res.cloudinary.com/dubu8yxkm/image/upload/v1754513796/Ankit_Raj_g2t95v.avif",
    coe: "JNV Bengaluru Urban",
    hall: "LBS",
    contacts: {
      mail: "ankiitrazz@gmail.com",
      linkedIn: "https://www.linkedin.com/in/ankit-raj-b164b5377",
      phone: "6201017742",
    },
    involvements: {
      soc: ["NSSC", "GYWS", "SF"],
      hall: [],
      council: [],
      iit: [],
      extra: "",
    },
  },
  {
    id: 22,
    name: "Mr. Mohar Biswas",
    branch: "CS",
    img: "https://res.cloudinary.com/dubu8yxkm/image/upload/v1754513802/Mohar_Biswas_gdrgaw.avif",
    coe: "JNV Bengaluru Urban",
    hall: "LBS",
    contacts: {
      mail: "2025Mohar@gmail.com",
      linkedIn: "https://www.linkedin.com/in/mohar-biswas-154208377",
      phone: "6296216400",
    },
    involvements: {
      soc: ["GYWS"],
      hall: [],
      council: [],
      iit: [],
      extra: "Physics Olympiad State Topper",
    },
  },
  {
    id: 24,
    name: "Mr. Pradeep",
    branch: "GG",
    img: "https://res.cloudinary.com/dubu8yxkm/image/upload/v1754513803/Pradeep_hr9nje.avif",
    coe: "Dakshana Valley",
    hall: "LBS",
    contacts: {
      mail: "manunaik852@gmail.com",
      linkedIn: "https://www.linkedin.com/in/pradeep-naik-b76540377",
      phone: "8660593670",
    },
    involvements: {
      soc: ["GYWS", "Spring Fest", "ECell"],
      hall: [],
      council: [],
      iit: [],
      extra: "RMO Qualified",
    },
  },
  {
    id: 25,
    name: "Mr. Priyansh Rathor",
    branch: "CS",
    img: "https://res.cloudinary.com/dubu8yxkm/image/upload/v1754513803/Priyansh_Rathor_aexigd.avif",
    coe: "JNV Bundi",
    hall: "LBS",
    contacts: {
      mail: "rathorpriyansh180407@gmail.com",
      linkedIn: "https://www.linkedin.com/in/priyansh-rathor-0244b7377",
      phone: "9024584966",
    },
    involvements: {
      soc: [],
      hall: [],
      council: [],
      iit: [],
      extra: "",
    },
  },
  {
    id: 26,
    name: "Mr. Rahul Atram",
    branch: "EE",
    img: "https://res.cloudinary.com/dubu8yxkm/image/upload/v1754513804/Rahul_Atram_bxcf4p.avif",
    coe: "Dakshana Valley",
    hall: "LBS",
    contacts: {
      mail: "atramrahul487@gmail.com",
      linkedIn: "https://www.linkedin.com/in/rahul-atram-73b75b377",
      phone: "9011556081",
    },
    involvements: {
      soc: ["GYWS", "TSS"],
      hall: [],
      council: [],
      iit: [],
      extra: "",
    },
  },
  {
    id: 27,
    name: "Mr. Rahul Rathore",
    branch: "CH",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1759576897/RahulRathore_hw0159.avif",
    coe: "Dakshana Valley",
    hall: "LBS",
    contacts: {
      mail: "rahulrathore27825@gmail.com",
      linkedIn: "https://www.linkedin.com/in/rahul-rathore-2a933a377",
      phone: "7723036335",
    },
    involvements: {
      soc: [],
      hall: ["Wing Representative"],
      council: [],
      iit: [],
      extra: "",
    },
  },
  {
    id: 28,
    name: "Mr. Rajat",
    branch: "ME",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1759576897/Rajat_bug8sz.avif",
    coe: "Dakshana Valley",
    hall: "LBS",
    contacts: {
      mail: "rajat808gothwal@gmail.com",
      linkedIn: "https://www.linkedin.com/in/rajat-gothwal-77859b377",
      phone: "7891606142",
    },
    involvements: {
      soc: [],
      hall: [],
      council: [],
      iit: [],
      extra: "",
    },
  },
  {
    id: 29,
    name: "Mr. Rajkumar Yadav",
    branch: "MA",
    img: "https://res.cloudinary.com/dubu8yxkm/image/upload/v1754513805/Rajkumar_Yadav_hwhtpe.avif",
    coe: "Dakshana Valley",
    hall: "LBS",
    contacts: {
      mail: "rajkumarydv25@kgpian.iitkgp.ac.in",
      linkedIn: "https://www.linkedin.com/in/rajkumar-yadav-0b8949378",
      phone: "9201455991",
    },
    involvements: {
      soc: ["KTJ"],
      hall: [],
      council: [],
      iit: [],
      extra: "",
    },
  },
  {
    id: 30,
    name: "Mr. Rinku Shakya",
    branch: "IE",
    img: "https://res.cloudinary.com/dubu8yxkm/image/upload/v1754513805/Rinku_Shakya_xyqnx4.avif",
    coe: "Dakshana Valley",
    hall: "LBS",
    contacts: {
      mail: "rinkooshakya625@gmail.com",
      linkedIn: "https://www.linkedin.com/in/rinkoo-shakya-985054301",
      phone: "8085350763",
    },
    involvements: {
      soc: ["Aroma"],
      hall: [],
      council: [],
      iit: [],
      extra: "",
    },
  },
  {
    id: 31,
    name: "Ms. Riya Vala",
    branch: "MA",
    img: "https://res.cloudinary.com/dubu8yxkm/image/upload/v1754513806/Riya_Vala_y41aoc.avif",
    coe: "Dakshana Valley",
    hall: "SNVH",
    contacts: {
      mail: "valabharat581@gmail.com",
      linkedIn: "https://www.linkedin.com/in/riya-vala-b97818377",
      phone: "9106920348",
    },
    involvements: {
      soc: ["KTJ"],
      hall: [],
      council: [],
      iit: [],
      extra: "",
    },
  },
  {
    id: 32,
    name: "Ms. Routhu Amulya",
    branch: "EE",
    img: "https://res.cloudinary.com/dubu8yxkm/image/upload/v1754513806/Routhu_Amulya_ycxntm.avif",
    coe: "JNV Bengaluru Urban",
    hall: "SNVH",
    contacts: {
      mail: "amulyarouth12@gmail.com",
      linkedIn: "https://www.linkedin.com/in/routhu-amulya-9451b7377",
      phone: "7569797035",
    },
    involvements: {
      soc: ["NSSC", "GYWS"],
      hall: [],
      council: [],
      iit: [],
      extra: "",
    },
  },
  {
    id: 33,
    name: "Ms. Sakshi Athole",
    branch: "ME",
    img: "https://res.cloudinary.com/dubu8yxkm/image/upload/v1754513806/Sakshi_Athole_xmnbhr.avif",
    coe: "Dakshana Valley",
    hall: "SNVH",
    contacts: {
      mail: "sakshiathole286@gmail.com",
      linkedIn: "https://www.linkedin.com/in/sakshi-athole-689a46377",
      phone: "8669092669",
    },
    involvements: {
      soc: ["Megalith"],
      hall: [],
      council: [],
      iit: [],
      extra: "",
    },
  },
  {
    id: 34,
    name: "Mr. Sandeep Neel",
    branch: "CI",
    img: "https://res.cloudinary.com/dubu8yxkm/image/upload/v1754531801/Sandeep_Neel_lrgkrx.avif",
    coe: "JNV Bundi",
    hall: "LBS",
    contacts: {
      mail: "neelsandeep05@gmail.com",
      linkedIn: "https://www.linkedin.com/in/sandeep-neel-5035a2377",
      phone: "7690974206",
    },
    involvements: {
      soc: [],
      hall: [],
      council: [],
      iit: [],
      extra: "Krida Gyan Pariksha Qualified",
    },
  },
  {
    id: 35,
    name: "Mr. Sarban Choudhary",
    branch: "CY",
    img: "https://res.cloudinary.com/dubu8yxkm/image/upload/v1754513806/Sarban_Choudhary_eqjquw.avif",
    coe: "Dakshana Valley",
    hall: "LBS",
    contacts: {
      mail: "sarbanchoudhary2719@gmail.com",
      linkedIn: "https://www.linkedin.com/in/sarban-choudhary-a425a3377",
      phone: "9317079814",
    },
    involvements: {
      soc: [],
      hall: [],
      council: [],
      iit: [],
      extra: "",
    },
  },
  {
    id: 36,
    name: "Mr. Sivang",
    branch: "IM",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1759576897/Sivang_o9x8qy.avif",
    coe: "Dakshana Valley",
    hall: "LBS",
    contacts: {
      mail: "sivangverma822@gmail.com",
      linkedIn: "https://www.linkedin.com/in/sivang-53766a377",
      phone: "8094519822",
    },
    involvements: {
      soc: [],
      hall: [],
      council: [],
      iit: [],
      extra: "",
    },
  },
  {
    id: 37,
    name: "Mr. Swagata Mondal",
    branch: "IM",
    img: "https://res.cloudinary.com/dubu8yxkm/image/upload/v1754513807/Swagata_Mondal_egdwv1.avif",
    coe: "Dakshana Valley",
    hall: "LBS",
    contacts: {
      mail: "mswagata412@gmail.com",
      linkedIn: "https://www.linkedin.com/in/swagata-mondal-4b5592377",
      phone: "7029095973",
    },
    involvements: {
      soc: ["GYWS"],
      hall: [],
      council: [],
      iit: [],
      extra: "",
    },
  },
  {
    id: 38,
    name: "Mr. Tarun Kumar",
    branch: "CS",
    img: "https://res.cloudinary.com/dubu8yxkm/image/upload/v1754513807/Tarun_Kumar_droa77.avif",
    coe: "JNV Bengaluru Urban",
    hall: "LBS",
    contacts: {
      mail: "omydeartarun@gmail.com",
      linkedIn: "https://www.linkedin.com/in/tarun-kumar-71a91b377",
      phone: "8745938891",
    },
    involvements: {
      soc: ["KodeinKGP", "KTJ"],
      hall: [],
      council: [],
      iit: [],
      extra: "",
    },
  },
  {
    id: 39,
    name: "Mr. Vidwathkalpa Gundaram",
    branch: "AI",
    img: "https://res.cloudinary.com/dubu8yxkm/image/upload/v1754513808/Vidwathkalpa_Gundaram_k3mzpe.avif",
    coe: "JNV Kottayam",
    hall: "LBS",
    contacts: {
      mail: "vidwathkalpa28@gmail.com",
      linkedIn: "https://www.linkedin.com/in/vidwathkalpa-gundaram-090331377",
      phone: "9490532928",
    },
    involvements: {
      soc: [],
      hall: [],
      council: [],
      iit: [],
      extra: "",
    },
  },
  {
    id: 40,
    name: "Mr. Yash Alhapuriya",
    branch: "AI",
    img: "https://res.cloudinary.com/dubu8yxkm/image/upload/v1754513808/Yash_Alhapuriya_h0rezt.avif",
    coe: "Dakshana Valley",
    hall: "LBS",
    contacts: {
      mail: "alhapuriyayash2005@gmail.com",
      linkedIn: "https://www.linkedin.com/in/yash-alhapuriya-28a204369",
      phone: "9755550853",
    },
    involvements: {
      soc: [],
      hall: [],
      council: [],
      iit: [],
      extra: "",
    },
  },
  {
    id: 41,
    name: "Mr. Chaudhari Yash",
    branch: "AI",
    img: "https://res.cloudinary.com/dubu8yxkm/image/upload/v1754513809/Yash_Chaudhari_akhenu.avif",
    coe: "Dakshana Valley",
    hall: "LBS",
    contacts: {
      mail: "yashchaudhari1401@gmail.com",
      linkedIn: "https://www.linkedin.com/in/yash-chaudhari-a07a4b377",
      phone: "7862933963",
    },
    involvements: {
      soc: ["SF", "GCA"],
      hall: [],
      council: [],
      iit: [],
      extra: "",
    },
  },
];

export default Intake2025Data;
