const Intake2023Data = [
  {
    index: 0,
    name: "Mr. Abhay Mishra",
    branch: "EC",
    mail: "abhaymishra77275@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1748288493/Abhay_Mishra_lflklg_zo84o1.avif",
    linkedIn: "",
    hall: "Azad",
  },
  {
    index: 1,
    name: "Mr. Abhinav Kumar Choudhary",
    branch: "AG",
    mail: "abhinavkumarchoudhary@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1748288494/Abhinav_Kumar_Chaudhary_ahsqwx_g0ynox.avif",
    linkedIn: "",
    hall: "RP",
  },
  {
    index: 2,
    name: "Ms. Akanksha Kushwaha",
    branch: "IE",
    mail: "akankshakushwaha0111@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1748288494/Akanksha_Kushwaha_gvn4ml_acho61.avif",
    linkedIn: "",
    hall: "MT",
  },
  {
    index: 3,
    name: "Mr. Amit Dinkar",
    branch: "AE",
    mail: "amiitd0704@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1748288495/Amit_Dinkar_fz2z2z_bs7bj4.avif",
    linkedIn: "https://www.linkedin.com/in/amit-dinkar-454b73288",
    hall: "MS",
  },
  {
    index: 4,
    name: "Mr. Animesh Mondal",
    branch: "IE",
    mail: "animeshtxt@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1748288495/Animesh_Mondal_ncvp4c_fxgjyh.avif",
    linkedIn: "https://www.linkedin.com/in/animesh-mondal-4b702527a/",
    hall: "MS",
  },
  {
    index: 5,
    name: "Mr. Anshuman Acharya",
    branch: "CH",
    mail: "anshuman2004@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1748288496/Anshuman_Acharya_rlaqrq_gw9a2l.avif",
    linkedIn: "",
    hall: "VS",
  },
  {
    index: 6,
    name: "Mr. Anushesh Jumale",
    branch: "IE",
    mail: "Anushesh@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1748288496/Anushesh_Jumale_wyjwp1_cfuwj5.avif",
    linkedIn: "",
    hall: "RP",
  },
  {
    index: 7,
    name: "Mr. Arnab Chakraborty",
    branch: "CH",
    mail: "I_am_arnab@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1748288497/Arnab_Chakraborty_so1pdv_zvlbll.avif",
    linkedIn: "https://www.linkedin.com/in/arnab-chakraborty-264a43289",
    hall: "Nehru",
  },
  {
    index: 8,
    name: "Mr. Arvind Meena",
    branch: "BT",
    mail: "arvindmeena@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1748288497/Arvind_Meena_zsll0a_gzpiej.avif",
    linkedIn: "https://www.linkedin.com/in/arvind-meena-78a258288",
    hall: "MMM",
  },
  {
    index: 9,
    name: "Mr. Ashutosh Ranjan",
    branch: "ME",
    mail: "ashutoshranjan@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1759170074/ashutoshRanjan_e8ddls.avif",
    linkedIn: "https://www.linkedin.com/in/ashutosh-ranjan-a33a4927a",
    hall: "RP",
  },
  {
    index: 10,
    name: "Mr. Ashwini Kumar",
    branch: "AG",
    mail: "ashwinikumar45@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1748288499/Ashwini_kumar_uggowl_pvbsw5.avif",
    linkedIn: "https://www.linkedin.com/in/wini045",
    hall: "RK",
  },
  {
    index: 11,
    name: "Mr. Bijaya Kumar Behera",
    branch: "BT",
    mail: "bijayabehera745@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1748288499/Bijay_Kumar_Behera_su8rmg_eiyvzb.avif",
    linkedIn: "",
    hall: "Nehru",
  },
  {
    index: 12,
    name: "Mr. Ganesh Vasuniya",
    branch: "AG",
    mail: "ganesh98@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1748288500/Ganesh_Vasuniya_lee4cu_jeukj9.avif",
    linkedIn: "https://www.linkedin.com/in/ganesh-vasuniya-02aba32b2",
    hall: "JCB",
  },
  {
    index: 13,
    name: "Ms. Hawa Khatoon",
    branch: "CH",
    mail: "Hawakhatoon131@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1748288500/Hawa_Khatoon_hpx4pq_u37b3w.avif",
    linkedIn: "https://in.linkedin.com/in/hawa-khatoon-362a7a2b6",
    hall: "MT",
  },
  {
    index: 14,
    name: "Ms. Jyoti Hembram",
    branch: "IE",
    mail: "jyotihembram.studyat@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1748288501/Jyoti_Hembram_jly0hq_gpnrkm.avif",
    linkedIn: "https://www.linkedin.com/in/jyoti-hembram-341512288",
    hall: "MT",
  },
  {
    index: 15,
    name: "Mr. Krishna Singha",
    branch: "CS",
    mail: "krishnasingha426@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1748288501/Krishna_Singha_kngavp_xh8qxv.avif",
    linkedIn: "https://www.linkedin.com/in/krishnasingha/",
    hall: "VS",
  },
  {
    index: 16,
    name: "Mr. Mohit Kumar",
    branch: "EC",
    mail: "mk8750351763@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747723437/Mohit_Kumar_h57d5w.avif",
    linkedIn: "",
    hall: "LLR",
  },
  {
    index: 17,
    name: "Mr. Nishant Meena",
    branch: "EE",
    mail: "meenanishant36@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1748288502/Nishant_Meena_bi57k1_qjlnt4.avif",
    linkedIn: "",
    hall: "ABV",
  },
  {
    index: 18,
    name: "Mr. Om Dabhade",
    branch: "IE",
    mail: "dabhadeom187@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1748288503/Om_Dabhade_z0sxjw_b6dacp.avif",
    linkedIn: "",
    hall: "Azad",
  },
  {
    index: 19,
    name: "Mr. Om Shanti",
    branch: "CS",
    mail: "oms409793@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1748288528/Om_Shanti_gcsvtk_x95b1l.avif",
    linkedIn: "http://linkedin.com/in/om-shanti-22885328o",
    hall: "Azad",
  },
  {
    index: 20,
    name: "Mr. Prabhat Kumar",
    branch: "MA",
    mail: "prabhatjha01@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1748288647/Prabhat_Jha_bot6r5_om76uc.avif",
    linkedIn: "https://www.linkedin.com/in/prabhat-kumar-134228255",
    hall: "ABV",
  },
  {
    index: 21,
    name: "Mr. Praveen Oraon",
    branch: "ME",
    mail: "praveenoraon518@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1748288647/Praveen_Oraon_zqeuwe_metoki.avif",
    linkedIn: "",
    hall: "Patel",
  },
  {
    index: 22,
    name: "Mr. Phrithiviraj Nunisa",
    branch: "AG",
    mail: "nunisaphrithviraj@gmail.com",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747723143/Avatar_avs1qx.avif",
    linkedIn: "",
    hall: "LLR",
  },
  {
    index: 23,
    name: "Mr. Raja Mandal",
    branch: "CS",
    mail: "rajamandal5346@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1748288648/Raja_Mandal_nmtbza_bjxypv.avif",
    linkedIn: "",
    hall: "RP",
  },
  {
    index: 24,
    name: "Mr. Ramesh Kumar Das",
    branch: "EE",
    mail: "kramesh1845@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1748288647/Ramesh_Kumar_mpfxxp_ohl7uz.avif",
    linkedIn: "",
    hall: "Nehru",
  },
  {
    index: 25,
    name: "Ms. Sangeeta Kumari Mandal",
    branch: "CS",
    mail: "sangeeta180703@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1748288648/Sangeeta_Kumari_Mandal_a35dfb_pdvsrh.avif",
    linkedIn: "",
    hall: "MT",
  },
  {
    index: 26,
    name: "Mr. Shani Maurya",
    branch: "IM",
    mail: "shauryashanisaini@gmail.com",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1748023103/Shani_Maurya_cpux6d.avif",
    linkedIn: "https://www.linkedin.com/in/shani8828",
    hall: "MMM",
  },
  {
    index: 27,
    name: "Mr. Shreyash Dhakate",
    branch: "IM",
    mail: "shreyashdhakate@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1748288648/Shreyash_Dhakate_nwu1vx_dvkjlw.avif",
    linkedIn: "",
    hall: "MMM",
  },
  {
    index: 28,
    name: "Mr. Subhajit Mondal",
    branch: "IM",
    mail: "subhajit2005@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1748288648/Subhajit_Mondal_odmvbq_gekon5.avif",
    linkedIn: "",
    hall: "RP",
  },
  {
    index: 29,
    name: "Mr. Subhajit Sarkar",
    branch: "EC",
    mail: "subhajit35sarkar@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1748288648/Subhajit_Sarkar_sjusnh_esnnwx.avif",
    linkedIn: "",
    hall: "MMM",
  },
  {
    index: 30,
    name: "Mr. Sukumar Singh",
    branch: "CS",
    mail: "sukumarsingh@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1748288649/Sukumar_qjkqpc_q4ny2m.avif",
    linkedIn: "",
    hall: "MS",
  },
  {
    index: 31,
    name: "Mr. Sunny",
    branch: "IE",
    mail: "sunnyscnt458@gmail.com",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1748288650/Sunny_lzoth5_x3clbm.avif",
    linkedIn: "https://www.linkedin.com/in/sunny-065a19288",
    hall: "Nehru",
  },
  {
    index: 32,
    name: "Mr. Suvadip Bhuiya",
    branch: "CS",
    mail: "suvadipbhuiya09@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1748288651/Suvadip_Bhaiya_xhzvsy_ssvutz.avif",
    linkedIn: "",
    hall: "Nehru",
  },
  {
    index: 33,
    name: "Mr. Swarup Jayaram Dhanavade",
    branch: "MI",
    mail: "swarupd@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747723597/Swarup_Dhanavade_ncjz8k.avif",
    linkedIn: "https://www.linkedin.com/in/swarup-dhanavade",
    hall: "Nehru",
  },
  {
    index: 34,
    name: "Mr. Vikash Rathore",
    branch: "CH",
    mail: "vikashrathore@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1748288651/Vikash_Rathore_pint2b_rylewt.avif",
    linkedIn: "",
    hall: "Patel",
  },
];

export default Intake2023Data;
