export const GenderWise = [
  { gender: "Male", count: 141 },
  { gender: "Female", count: 18 },
];
export const BatchWise = [
  { year: "25", count: 42 },
  { year: "24", count: 46 },
  { year: "23", count: 35 },
  { year: "22", count: 27 },
  { year: "21", count: 9 },
];
export const BranchWise = [
  { branch: "AE", count: "5" },
  { branch: "AG", count: "9" },
  { branch: "AI", count: "4" },
  { branch: "BT", count: "4" },
  { branch: "CE", count: "1" },
  { branch: "CH", count: "12" },
  { branch: "CI", count: "1" },
  { branch: "CS", count: "22" },
  { branch: "CY", count: "3" },
  { branch: "EC", count: "12" },
  { branch: "EE", count: "12" },
  { branch: "EX", count: "2" },
  { branch: "HS", count: "1" },
  { branch: "IE", count: "15" },
  { branch: "IM", count: "10" },
  { branch: "MA", count: "9" },
  { branch: "ME", count: "11" },
  { branch: "MF", count: "2" },
  { branch: "MI", count: "8" },
  { branch: "NA", count: "6" },
  { branch: "MT", count: "9" },
  { branch: "GG", count: "1" },
];
export const HallWise = [
  { hall: "ABV", count: "2" },
  { hall: "Azad", count: "10" },
  { hall: "HJB", count: "1" },
  { hall: "JCB", count: "2" },
  { hall: "LLR", count: "6" },
  { hall: "LBS", count: "38" },
  { hall: "MS", count: "10" },
  { hall: "MMM", count: "18" },
  { hall: "MT", count: "5" },
  { hall: "Nehru", count: "11" },
  { hall: "Null", count: "2" },
  { hall: "Patel", count: "8" },
  { hall: "RK", count: "11" },
  { hall: "RP", count: "17" },
  { hall: "SN/IG", count: "4" },
  { hall: "SNVH", count: "9" },
  { hall: "VS", count: "5" },
];
export const COEWise = [
  { coe: "DV", count: 59 },
  { coe: "JNV BU", count: 47 },
  { coe: "JNV Bundi", count: 14 },
  { coe: "JNV Kottayam", count: 12 },
  { coe: "JNV Lucknow", count: 5 },
  { coe: "JNV RR", count: 7 },
];
