export const CouncilData24 = [
  {
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1748012053/Ashutosh_wvgdts.avif",
    title: "Mr. Ashutosh ",
    portfolio: "Vice President, Events - DST & Freshmen",
    mobile: "+91 9058887078",
    mail: "ashutosh.daan@gmail.com",
    year: "5th",
  },
  {
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747723339/Paramjeet_Saini_xolxxj.avif",
    title: "Mr. Paramjeet Saini",
    portfolio: "Senior Secretary, DST(JNV)",
    mail: "paramjeetsaini@kgpian.iitkgp.ac.in",
    mobile: "+91 6397189676",
    year: "4th",
  },
  {
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1748023103/Shani_Maurya_cpux6d.avif",
    title: "Mr. Shani Maurya",
    portfolio: "College Representative, IIT Kharagpur",
    mail: "shauryashanisaini@gmail.com",
    mobile: "+91 9555439091",
    year: "3rd",
  },
  {
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747723437/Mohit_Kumar_h57d5w.avif",
    title: "Mr. Mohit Kumar",
    portfolio: "Junior Secretary, DST(Non-JNV)",
    mail: "mk8750351763@kgpian.iitkgp.ac.in",
    mobile: "+91 8384078167",
    year: "3rd",
  },
  {
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747723597/Swarup_Dhanavade_ncjz8k.avif",
    title: "Mr. Swarup Dhanavade",
    portfolio: "Junior Secretary, DST(JNV)",
    mail: "swarupd@kgpian.iitkgp.ac.in",
    mobile: "+91 9423751729",
    year: "3rd",
  },
];

export const CouncilData25 = [
  {
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747723339/Paramjeet_Saini_xolxxj.avif",
    title: "Mr. Paramjeet Saini",
    portfolio: "VP, Events - DST & Freshmen",
    mail: "paramjeetsaini@kgpian.iitkgp.ac.in",
    mobile: "+91 6397189676",
    year: "4th",
  },
  {
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1748023103/Shani_Maurya_cpux6d.avif",
    title: "Mr. Shani Maurya",
    portfolio: "Sr. Secy, Placement Committee",
    mail: "shauryashanisaini@gmail.com",
    mobile: "+91 9555439091",
    year: "3rd",
  },
  {
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747723597/Swarup_Dhanavade_ncjz8k.avif",
    title: "Mr. Swarup Dhanavade",
    portfolio: "Sr. Secy, DST(JNV)",
    mail: "swarupd@kgpian.iitkgp.ac.in",
    mobile: "+91 9423751729",
    year: "3rd",
  },
  {
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1760806421/UttamMeghwal_ju8s0v.avif",
    title: "Mr. Uttam Meghwal",
    portfolio: "CR-I, IIT Kharagpur",
    mail: "Uttammeghwal.24@kgpian.iitkgp.ac.in",
    mobile: "+916264607383",
    year: "2nd",
  },
  {
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1760805714/ShivamAhirwar_mlrqzr.avif",
    title: "Mr. Shivam Ahirwar",
    portfolio: "CR-II, IIT Kharagpur",
    mail: "ahirwarshivam7049@gmail.com",
    mobile: "+917049996597",
    year: "2nd",
  },{
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1759676250/AbhinamDutta_xqj8rt.avif",
    title: "Mr. Abhinam Dutta",
    portfolio: "Jr. Secy, DST(JNV)",
    mail: "abhinamdutta.24@kgpian.iitkgp.ac.in",
    mobile: "+917631504442",
    year: "2nd",
  },
  {
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1759676251/Monika_afmvu1.avif",
    title: "Ms. Monika Dhakad",
    portfolio: "Jr. Secy, DST(Non-JNV)",
    mail: "monikadhakad135.24@kgpian.iitkgp.ac.in",
    mobile: "+91 7770951080",
    year: "2nd",
  },
  {
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747753917/Akhil_Dixit_qlwruw_s0bq6w.avif",
    title: "Mr. Akhilesh Dixit",
    portfolio: "Jr. Secy, Placement Committee",
    mail: "akhileshdixit07.24@kgpian.iitkgp.ac.in",
    mobile: "+917307044974",
    year: "2nd",
  },
];
export const demo=[
  
    {
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747723143/Avatar_avs1qx.avif",
    title: "Will be declared soon.",
    portfolio: "---",
    mail: "---",
    mobile: "+91 XXXXXXXXXX",
    year: "-",
  },
  
]